set autoindent
set cindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=100
set visualbell
set backspace=indent,eol,start
set number
set clipboard=unnamed
syntax on
colorscheme zellner
